name: Favorites characters
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: drowning-in-codes/metrics@master
        with:
          filename: metrics.plugin.anilist.characters.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_medias: anime, favorites, watching
          plugin_anilist_sections: characters
          plugin_anilist_limit_characters: 13
 
  
        

   
